[project]
name = "mycli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.2",
    "tox>=4.25.0",
    "tox-uv>=1.25.0",
]
